### PR TITLE
Added capability to pass params when success and multiple listeners

### PR DESCRIPTION
**Pull request by Tavernari**
Hi,

In my case I needed to receive data on JobListener, so to resolve that I put a parameter on success, and I did other thing about listener, for organization I change JobListener to array because now I can put multiple Listeners doing specific things.

Look if it make sense for you.

Best,
Victor C Tavernari

### CODE REVIEW

**Comment by lucas34** [comment]
Hi, To me the multi-listener is too much overhead. Users can easily register a register that will dispatch to multiples other listener.

With this approach the the lib is kept minimal and the client can decide the internal data structure. Array will not be super suitable if we want O(1) for item removal. However Set will not match if the listener order matter.

Here is a code snipped that you can use that should work on client side

```swift
public class JobListenerDelegate: JobListener {

    public var actual: [JobListener] = [JobListener]()

    public func onBeforeRun(job: JobInfo) {
        actual.forEach { listener in
            listener.onBeforeRun(job: job)
        }
    }

    public func onAfterRun(job: JobInfo, result: JobCompletion) {
        actual.forEach { listener in
            listener.onAfterRun(job: job, result: result)
        }
    }

    public func onTerminated(job: JobInfo, result: JobCompletion) {
        actual.forEach { listener in
            listener.onTerminated(job: job, result: result)
        }
    }
}
```

**Comment by Tavernari** [comment]
Hi @lucas34,

I added another feature here, now we can call `swiftQueueManager.removeAllPersistedOperations()`.

I did it because I had a problem on logout situation and when I back to the app it starts again the queue, so it was responsible for crash.

**Comment by Tavernari** [comment]
> 

I will change

**Comment by lucas34** [comment]
Adding a method to remove All job before the SwiftQueueManager is built is a good idea. I'll submit MR for this in #275.

However for the main idea on this MR of passing the result of the job to the listener I quite don't agree with this for 2 reason. 
- The listener is mainly to have side effect for the job. In this case the listener can actually be used as a main JobHandler so that will break the encapsulation principle.
- The main protocol (JobResult) will change and that will be a huge breaking change for the library. We can eventually consider for SwiftQueue 5

**Pull request closed without merging**
